export const DEFAULT_LOG_LEVEL = 'info';

export const LOGGER_TIMESTAMP_FORMAT = 'YYYY-MM-DDTHH:mm:ss.SSSZ';

export const CLOUDWATCH_MAX_BATCH_SIZE = 10_000;

export const CLOUDWATCH_MAX_BATCH_BYTES = 1_048_576;

export const CLOUDWATCH_LOG_EVENT_OVERHEAD_BYTES = 26;

export const DEFAULT_CLOUDWATCH_FLUSH_INTERVAL_MS = 5_000;

export const DEFAULT_CLOUDWATCH_MAX_BUFFERED_EVENTS = 50_000;

export const DEFAULT_CLOUDWATCH_ERROR_REPORT_INTERVAL_MS = 60_000;
